$primary = rgb(6785e4)
$surface = rgb(0e162f)
$secondary = rgb(7c5cd6)
$error = rgb(8a2c27)
$tertiary = rgb(b662d0)
$surface_lowest = rgb(070b18)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
