github.com:
    users:
        zcn15:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: zcn15
